/**
 * AI 生成内容标识（tasks 10.3）。
 *
 * 合规依据：《人工智能生成合成内容标识办法》要求生成内容同时具备
 * **显式标识**（用户可见）与**隐式标识**（文件元数据）。分享时不得默认去除。
 *
 * 三层：
 *   1. 页面显式标识——API 响应里带 `disclosure` 字段（已在 plans 路由实现）
 *   2. 导出可见水印——图片右下角文字水印
 *   3. 文件元数据隐式标识——PNG 写 tEXt 块，JPEG 写 COM 注释段（0xFFFE）。
 *      两者都能被 exiftool 这类通用工具读出。
 *      ⚠ 不是 APP11/JUMBF——那是 C2PA 级来源凭证的载体，需要签名链，
 *      当前只做「可读出的生成标记」，够满足标识要求。若将来要做 C2PA，
 *      升级路径是 APP11 而非扩展 COM。
 *
 * 供应商侧也支持水印（Volcengine 的 `logo_info` 参数），但我们不依赖它：
 * 供应商参数变更、或换供应商时标识就丢了，而这是法定义务。自己加一层更可靠。
 */

export const AI_DISCLOSURE_TEXT = "AI生成模拟效果";
export const AI_DISCLOSURE_TEXT_EN = "Generated by AI";

/** 页面显式标识（API 响应用） */
export function buildDisclosure(opts: { isSimulated: boolean; basedOnSelfReported?: boolean }): string {
  const parts = [AI_DISCLOSURE_TEXT];
  if (opts.basedOnSelfReported) parts.push("基于你勾选的完成情况生成");
  return parts.join(" · ");
}

/**
 * 写入 PNG 的隐式标识。
 *
 * PNG 用 tEXt chunk（键值对文本块），插在 IHDR 之后。
 * 刻意手写而不引入图像库：只是插一个 chunk，引入 sharp/jimp 这类重依赖
 * 为了这点事不值得，而且它们会重编码图片（改变像素、增大体积）。
 */
export function embedPngMetadata(png: Buffer, metadata: Record<string, string>): Buffer {
  const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  if (!png.subarray(0, 8).equals(PNG_SIGNATURE)) return png; // 不是 PNG 就原样返回

  // IHDR chunk: 长度(4) + 类型(4) + 数据(13) + CRC(4) = 25 字节，紧跟签名之后
  const insertAt = 8 + 25;
  const chunks: Buffer[] = [png.subarray(0, insertAt)];

  for (const [key, value] of Object.entries(metadata)) {
    const data = Buffer.concat([Buffer.from(key, "latin1"), Buffer.from([0]), Buffer.from(value, "utf-8")]);
    const length = Buffer.alloc(4);
    length.writeUInt32BE(data.length);
    const type = Buffer.from("tEXt", "latin1");
    const crc = Buffer.alloc(4);
    crc.writeUInt32BE(crc32(Buffer.concat([type, data])) >>> 0);
    chunks.push(length, type, data, crc);
  }

  chunks.push(png.subarray(insertAt));
  return Buffer.concat(chunks);
}

/** PNG chunk 校验用的 CRC-32 */
function crc32(buf: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of buf) {
    crc ^= byte;
    for (let i = 0; i < 8; i++) {
      crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

/** 读回隐式标识，用于验证标识确实写进去了 */
export function readPngMetadata(png: Buffer): Record<string, string> {
  const out: Record<string, string> = {};
  let offset = 8;
  while (offset + 8 <= png.length) {
    const length = png.readUInt32BE(offset);
    const type = png.subarray(offset + 4, offset + 8).toString("latin1");
    if (type === "tEXt") {
      const data = png.subarray(offset + 8, offset + 8 + length);
      const sep = data.indexOf(0);
      if (sep > 0) {
        out[data.subarray(0, sep).toString("latin1")] = data.subarray(sep + 1).toString("utf-8");
      }
    }
    if (type === "IEND") break;
    offset += 12 + length;
  }
  return out;
}

/** 生成写入图片的标准元数据集 */
export function buildAiMetadata(opts: { provider?: string; generatedAt?: string; planId?: string }): Record<string, string> {
  return {
    // 通用键，图片查看器普遍能显示
    Software: "BetterMeet",
    Comment: `${AI_DISCLOSURE_TEXT} / ${AI_DISCLOSURE_TEXT_EN}`,
    // 合规要求的生成标记
    "AI-Generated": "true",
    "AI-Provider": opts.provider ?? "unknown",
    "AI-Generated-At": opts.generatedAt ?? new Date().toISOString(),
    ...(opts.planId ? { "AI-Plan-Id": opts.planId } : {}),
  };
}
